<a href="https://colab.research.google.com/github/TakeshiYoshikawa/Aula9/blob/master/Aula9_ArthurYoshikawa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as npr
import math

## Resolução de um Sistema Triangular Superior

In [0]:
def solveUpperTriangular(A,b):
    # m são linhas, e n são as colunas
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    x = np.zeros(n)
    
    x[n-1] = b[n-1]/A[n-1,n-1]
    
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k,n):
            s += A[k][j]*x[j]
            x[k] = (b[k] - s)/A[k,k]
            
    return x

## Eliminação de Gauss

In [35]:
def gaussElimination(A,b):
    n = len(A)
    
    if(np.size(b) != n):
        raise SizeError("Incompatible sizes between matrix A and vector b.")
        
    # k is pivot_row
    for k in range(n-1):
        #i is the row being analyzed.
        for i in range(k+1, n):
            m = A[i,k]/A[k,k]
            A[i,k] = 0
            print(A,'\n')
            # j is column index.
            for j in range(k+1, n):
                A[i,j] = A[i,j] - m*A[k,j]
            b[i] = b[i] - m*b[k]
    
    
    x = np.zeros(n)
    k = n-1
    
    x[k] = b[k]/A[k,k]
    
    while(k >= 0):
        s = np.dot(A[k,k+1:],x[k+1:])
        x[k] = (b[k] - s) / A[k,k]
        k -= 1
    return x


A = np.array([[3,2,4],[1,1,2],[4,3,-2]], dtype='float')
b = np.array([1,2,3], dtype='float')

print('Utilizando numpy:',np.linalg.solve(A,b))
print('Resolvendo pela eliminação gaussiana:\n',gaussElimination(A,b))

Utilizando numpy: [-3.  5.  0.]
[[ 3.  2.  4.]
 [ 0.  1.  2.]
 [ 4.  3. -2.]] 

[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          3.         -2.        ]] 

[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -7.33333333]] 

Resolvendo pela eliminação gaussiana:
 [-3.00000000e+00  5.00000000e+00  5.55111512e-17]


## Analisar a Eliminação para o sistema dado no Google: Gauss Elimination Wiki

In [36]:
A = np.array([[1,3,1],[1,1,-1],[3,11,5]], dtype='float') 
b = np.array([9,1,35], dtype='float')
print('Determinante de A',np.linalg.det(A))
print('\nA eliminação não foi bem sucedida devido ao fato do determinante = 0. É necessário a utilização de outra técnica para redução de erros de precisão.')
print('\nResolução do sistema via eliminação gaussiana\n',gaussElimination(A,b))

Determinante de A 0.0

A eliminação não foi bem sucedida devido ao fato do determinante = 0. É necessário a utilização de outra técnica para redução de erros de precisão.
[[ 1.  3.  1.]
 [ 0.  1. -1.]
 [ 3. 11.  5.]] 

[[ 1.  3.  1.]
 [ 0. -2. -2.]
 [ 0. 11.  5.]] 

[[ 1.  3.  1.]
 [ 0. -2. -2.]
 [ 0.  0.  2.]] 


Resolução do sistema via eliminação gaussiana
 [nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in double_scalars


## Executar melhorias na Eliminação Gaussiana

Melhoria 1 - Se elemento zero abaixo do pivô: continue. 

Melhoria 2 - Se um dos pivôs for zero mostrar mensagem de erro

Melhoria 3 - Se determinante = 0: mensagem de erro. Else: aplicar gaussElmination

In [37]:
def improvedGaussElimination(A,b):
    n = len(A)
    print('Verify determinant:',np.linalg.det(A))
    
    if(np.size(b) != n):
        raise SizeError("Incompatible sizes between matrix A and vector b.")
    if(np.linalg.det(A) == 0):
        return "Singular Matrix - Determinant equals 0, unable to process given matrix"
        
    for k in range(n):
        #A[k,k] refers to chosen pivot per iteration.
        if(A[k,k] == 0):
            print("Pivot equals 0 (Error)")
            continue
            
        for i in range(k+1, n):
            #A[i,k] é o elemento abaixo do pivô.
            if(A[i,k] == 0):
                continue
            m = A[i,k]/A[k,k]
            A[i,k] = 0
            print(A,'\n')
            
            for j in range(k+1, n):
                A[i,j] = A[i,j] - m*A[k,j]
            b[i] = b[i] - m*b[k]
    
    x = np.zeros(n)
    k = n-1
    
    x[k] = b[k]/A[k,k]
    
    while(k >= 0):
        s = np.dot(A[k,k+1:],x[k+1:])
        x[k] = (b[k] - s) / A[k,k]
        k -= 1

    return x


A = np.array([[1,3,1],[1,1,-1],[3,11,5]], dtype='float')
b = np.array([9,1,35], dtype='float')
#A = np.array([[3,2,4,-1],[0,1,0,3],[0,-3,-5,7],[0,2,4,0]], dtype='float')
#b = np.array([5,6,7,15], dtype='float')


print('Resolvendo pela eliminação gaussiana:\n',improvedGaussElimination(A,b))

Verify determinant: 0.0
Resolvendo pela eliminação gaussiana:
 Singular Matrix - Determinant equals 0, unable to process given matrix


## Desenvolva um def para o Pivotamento Parcial

In [38]:
def doPartialPivoting(A, b):
    n = len(A)
    x = np.zeros(n)
    
    #Points incompability between matrix and vector
    if (np.size(b) != n):
        print('Incompatible sizes between A =', n, 'and b =', np.size(b))
        return -1
    
    # Elimination
    for k in range(n-1):
        if A[k,k] == 0:
            print('Pivot equals zero.')     
            return -1
        
        # Pivot
        maxindex = np.argmax(abs(A[k:,k])) + k
        if (A[maxindex, k] == 0):
            print('Determinant equals 0.')
            return -1
        
        if (maxindex != k):
            A[[k,maxindex]] = A[[maxindex, k]]
            b[[k,maxindex]] = b[[maxindex, k]]
            
        #Eliminate for each row
        for i in range(k+1, n):
            m = A[i,k]/A[k,k]
            A[i, k:] = A[i, k:] - m*A[k, k:]
            b[i] = b[i] - m*b[k]
    
    # Back Substitution
    for k in range(n-1, -1, -1):
        s = np.dot(A[k,k+1:],x[k+1:])
        x[k] = (b[k] - s)/A[k,k]
        
    return A,x


A = np.array([[3,2,4],[1,1,2],[4,3,-2]], dtype='float')
b = np.array([1,2,3], dtype='float')
#A = np.array([[2,2,2],[2,-2,2],[2,-2,-2]], dtype='float')
#b = np.array([20,8,0], dtype='float')
#A = np.array([[1,3,1],[1,1,-1],[3,11,5]], dtype='float')
#b = np.array([9,1,35], dtype='float')

print('x* =',doPartialPivoting(A,b))

x* = (array([[ 4.  ,  3.  , -2.  ],
       [ 0.  ,  0.25,  2.5 ],
       [ 0.  ,  0.  ,  8.  ]]), array([-3.,  5.,  0.]))


## Considere o seguinte sistema utilizando o pivotamento parcial

In [39]:
A = np.array([[0.0002,2],[2,2]], dtype='float')
b = np.array([5,6], dtype='float')

print('x_ =',doPartialPivoting(A,b))

x_ = (array([[2.    , 2.    ],
       [0.    , 1.9998]]), array([0.50005001, 2.49994999]))


## Desenvolva uma Máquina com precisão t = 3 dígitos


Exigência 1: Obter a solução de um sistema linear com e sem pivotamento parcial.

Exigência 2: O def deverá possuir como parâmetro: a matriz(A), vetor(b), e o dígito(t)

Exigência 3: Retornar a resposta do sistema e verifica se ela está correta

Exigência 4: Desenvolver um código genérico que consiga receber uma matrix quadrática de qualquer dimensão. Nota: Usar o exemplo apresentado em sala de aula.

In [40]:
def computer(value, decimal_limit, min_exp = -3, max_exp = 3):
    exp = 0
    
    if(value == 0):
        return 0
        
    #Enquanto o valor for menor que 0.1, multiplica por 10.
    while(abs(value) < 0.1):
        value *= 10
        exp -= 1
    
    #Enquanto o valor for maior que 1, divide o valor por 10.
    while(abs(value) > 1):
        value /= 10
        exp += 1

    #Indica se o expoente for maior ou menor que o limite, indica o underflow ou overflow.    
    '''
    if(exp > max_exp):
        print('Overflow. Try another input')
        return
    elif(exp < min_exp):
        print('Underflow')
        return 0
    
    else:
        print('Truncamento:', value, '. 10 ^', exp)
    '''
    
    return round(value, decimal_limit)*10**exp
        
computer(0.0002,3)

0.0002

In [43]:
# Escreva "Sem Pivotamento Parcial": Para executar a função que faz somente a eliminação gaussiana
# Escreva "Com Pivotamento Parcial": Para executar a função que obtém a solução utilizando a eliminação com pivotamento parcial.

def threeDigitMachine(A,b,t, mode):
    row = np.size(A[0])
    column = np.size(A[1])
    row1 = np.size(b)
    
    #This step adjust all A's elements to 3-digits precision machine
    for i in range(row):
        for j in range(column):
            A[i,j] = computer(A[i,j],t)

    for k in range(row1):
        b[k] = computer(b[k],t)

    #Escolhe a forma de obtenção da solução dependendo do modo escolhido.
    if(mode == 'Com Pivotamento Parcial'):
        return doPartialPivoting(A,b)
    else:
        return improvedGaussElimination(A,b)
#-------------------------------------------------------------------------------------------------------------------------------#

#A = np.array([[3,2,4],[1,1,2],[4,3,-2]], dtype='float')
#b = np.array([1,2,3], dtype='float')
A = np.array([[0.0002,2],[2,2]], dtype='float')
b = np.array([5,6], dtype='float')
#A = np.array([[3,2,4,-1],[0,1,0,3],[0,-3,-5,7],[0,2,4,0]], dtype='float')
#b = np.array([5,6,7,15], dtype='float')
#A = np.array([[1,1,-2,1,3,-1],[2,-1,1,2,1,-3],[1,3,-3,-1,2,1],[5,2,-1,-1,2,1],[-3,-1,2,3,1,3],[4,3,1,-6,-3,-2]],dtype='float')
#b = np.array([4,20,-15,-3,16,-27],dtype='float')             
t = 3

print('x =',threeDigitMachine(A,b,t,'Sem Pivotamento Parcial'))
print('Usando o numpy:',np.linalg.solve(A,b))

Verify determinant: -3.999599999999999
[[2.e-04 2.e+00]
 [0.e+00 2.e+00]] 

x = [0.50005    2.49994999]
Usando o numpy: [0.50005    2.49994999]
